name: 02- Variables & Conetexts
on: 
  workflow_dispatch: 
  
# LEVEL 1: Workflow-level env vars
# Available in EVERY job and EVERY step in this workflow

env:
  APP_NAME: healthcare-claims
  VERSION: 1.0.0
  AWS_REGION: us-east-1
jobs:
  learn-variables:
    runs-on: ubuntu-latest

    # LEVEL 2: Job-level env vars
    # Available in EVERY step inside THIS job only
    env:
      JOB_ENV : prod
    steps:
      - name: Print Workflow level Env's
        run: |
          echo "App Name: ${{env.APP_NAME}}"
          echo "AWS REgion: ${{env.AWS_REGION}}"
      - name: Print Job level Env's
        run: |
          echo "Job Env Name: ${{env.JOB_ENV}}"
      - name: Print step level Env's
        env:
          greetings: "Hello from Step Env"
        run: |
          echo "${{greetings}}"
      - name: Print github contexts
        run: |
          echo "Repository ${{github.repository}}"
          echo "Owner ${{github.repository_owner}}"
          echo "Triggered by ${{github.actor}}"
          echo "Branch ${{github.ref_name}}"
      - name: Dynamic variables with env and contexts
        run: |
          Image_Tag=${{env.APP_NAME}}:${{env.VERSION}}
          echo "Docker Image Tag would be: $Image_Tag"
          echo "Full Path ${{github.repository_owner}}/$Image_Tag"
        
