name: 05 Triggers
on: 
# MULTIPLE TRIGGERS: a workflow can have more than one trigger
# This workflow fires on ANY of these events
  workflow_dispatch: 
  push: 
    branches: 
      - main
      - develop
    paths: 
      - 'src/**'
      - '.github/workflows/**'
      - 'DockerFile'
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
  schedule:
    - cron: '0 9 * * 1-5'
jobs:
  detcet-trigger:
    name: Detect what triggerred this run
    runs-on: ubuntu-latest
    steps:
      - name: show what triggered this workflow
        run: |
          echo "Triggered on ${{github.action}}"
          echo "Triggered by ${{github.actor}}"
          echo "Branch ${{github.ref_name}}"
      - name: Step that only runs on push
        if: github.event_name == 'push'
        run: echo "this is triggered on push"
      - name: step that runs only on pull request
        if: github.event_name == 'pull_request'
        run: echo "This is triggred on pull request"
      - name: step that run on manual run
        if: github.event_name == 'workflow_dispatch'
        run: echo "this is triggered on manual run"
      
