name: 10 secrets
on: 
  workflow_dispatch: 
jobs:
  fetch-secret:
    runs-on: ubuntu-latest
    env:
      APIKEY: ${{secrets.MY_API_KEY}}
    steps:
      - name: confirm secret is vaialble
        run: echo "Key is ${{env.APIKEY}}"
      - name: Fetch secret directly
        run: echo "secret is ${{secrets.MY_API_KEY}}"
    
