name: 12 Push ECR
on: 
  workflow_dispatch: 
  push: 
    branches: 
      - main
    paths: 
      - 'src/**'
      - 'Dockerfile'
permissions: 
  id-token: write
  contents: read
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image: ${{steps.build.outputs.image}}
    steps:
      - name: clone repo
        uses: actions/checkout@v4
      - name: configure aws creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.AWS_ROLE_ARN}}
          aws-region: us-east-1
      - name: login to ECR 
        uses: aws-actions/amazon-ecr-login@v2

      - name: build tag and push
        id: build
        env:
          REGISTRY: ${{secrets.ECR_REGISTRY}}
          REPOSITORY: claims-service
          IMAGE_TAG: ${{github.sha}}
        run: | 
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG . 
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          echo "image=$REGISTRY/$REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
      - name: smoke test on pushed image
        env:
          REGISTRY: ${{ secrets.ECR_REGISTRY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker pull $REGISTRY/claims-service:$IMAGE_TAG 
          docker run --rm $REGISTRY/claims-service:$IMAGE_TAG
          
          
